name: SwiftCart API - Build and Deploy to Production

on:
  push:
    branches: [ "main" ]
    paths:
      - 'backend/**'

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repo
      uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./backend
        push: true
        platforms: linux/arm64
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/swiftcart-api:latest

  deploy:
  
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: SSH & Deploy to EC2
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          docker stop swiftcart-api
          docker rm swiftcart-api
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/swiftcart-api:latest
          docker run --env-file .swiftcart/config/.env -d --name swiftcart-api -p 8180:8080 ${{ secrets.DOCKERHUB_USERNAME }}/swiftcart-api:latest
      
